development: &default
  adapter: postgresql
  database: donors_development
  encoding: utf8
  host: <%= ENV.fetch("DB_HOST") %>
  min_messages: warning
  password:
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  username: <%= ENV.fetch("DB_USER", "postgres") %>

test:
  <<: *default
  database: donors_test

production: &deploy
  adapter: postgresql
  database: assemble_registry
  encoding: utf8
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
  min_messages: warning
  password:
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  username: <%= ENV.fetch("DB_USER", "postgres") %>

staging: *deploy
